# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

User.create!([
  { :email => "amcugs@gmail.com",  :name => "Andrew Cummings", :password => "password", :password_confirmation => "password"},
  { :email => "jessekevon@gmail.com",  :name => "Jesse Kevon", :password => "password", :password_confirmation => "password"},
])
